CREATE TABLE categories (
id SERIAL PRIMARY KEY,
name VARCHAR (255)

);

CREATE TABLE services (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  price INTEGER NOT NULL,
  category_id INTEGER NOT NULL REFERENCES categories (id) ON DELETE CASCADE,
  active BOOLEAN DEFAULT TRUE
);